### ISSUE TITLE
Failed to unpack BitterSmile.pkg

### ISSUE THREAD

**Issue by terminator399** [soarqin/finalhe#86]
hi,

i had this error with finahe. i didnt found any solution.  thanks for resolving it

![Capture](https://user-images.githubusercontent.com/68700209/88303348-99fe3a00-cd0f-11ea-8ada-1fddaa204016.PNG)

**Comment by HitsuMaruku** [comment]
Can confirm I am also receiving this error. I am using the latest FinalHe (1.92), and I am using a JP Vita on 3.73. I am connected to my PC using a USB cable, and am running Windows 10, and have installed the QCMA driver.

I've tried running the application normally and using Run as Administrator, and deleting the data folder and force-closing the FinalHe process in between some (but not all) of the attempts. Download and Verify steps process normally; it runs unpacking and gets to 99% before pausing a few seconds and reading the above failed to unpack message.

If I can give any additional information to assist with diagnosing or resolving this issue, please let me know. Thank you very much.

**Comment by terminator399** [comment]
i fixed it. simply check "trim" and it's working

**Comment by Kiel97** [comment]
For me it worked with closed QCMA application

**Comment by bluetonian** [comment]
I tired using the trim option and it still won't unpack. Has anyone found any other solution?

**Comment by NeonLightning** [comment]
> For me it worked with closed QCMA application

it's known that finalhe can't work with qcma open. qcma will intercept the stuff finalhe is trying to do

**Comment by linjunway** [comment]
I also have the same problem. But the issue arose because I initially pressed the Let's Go button without knowing that the arrow expanded to show the additional files to add vitadeploy. Hence, I tried to backtrack and redo it but resulted in the error.
